# Week 1 

The purpose of this week's exercise is twofold: First, to introduce you to Numpy and making you familiar with the library and some of its pitfalls. Second, you will apply this to estimate the linear model using OLS.

(Jupyter Basics) A few things to note about Jupyter Notebook (ipynb files). (1) Notebooks may run cells individually by selecting a cell and using ctrl + enter. (2) Each notebook runs on a kernel which is selected by the user the first time a cell is run. (3) The kernel "stores" variables as the code is run. To utilize code in a proceeding cell, it is neccessary to run the previous cell. Be careful with overlapping variable names across cells. It becomes messy to clean up.

* The kernel is your installation of Python. Make sure your installation of Python is visible to your environment.

Please note that some of the exercises are purposefully made to return errors. Take the time to identify why they occur.

## A short introduction to Numpy and Linear Algebra (Linalg)
First, import all necessary packages. If you are missing a package, you can either install it through your terminal using pip, or an Anaconda terminal using conda.

In [12]:
!pip install numpy
!pip install pandas
!pip install tabulate
!pip install matplotlib


533.91s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


539.59s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


545.16s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


550.72s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 6.6 MB/s  0:00:01m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 11.4 MB/s  0:00:00 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 13.3 MB/s  0:00:00 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]


In [71]:
import numpy as np # We import the package numpy and name it "np"
from numpy import linalg as la 
# We import the subpackage linalg from numpy and name it "la". 
# In most cases, importing a subpackage is not neccessary when the overarching package has been imported, 
# although lacking dependencies may change functionality in some cases.
from numpy import random as random
from tabulate import tabulate
#(NB if you havent got tabulate yet, install it using !pip install tabulate)
from matplotlib import pyplot as plt

### Entering matrices manually
To create a $1\times9$ *row* vector write,

In [14]:
row = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(row)

[1 2 3 4 5 6 7 8 9]


To create a $9\times1$ *column* vector write,

In [15]:
col = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9]])
print(col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


An easier method is to define a row vector, and transpose it. Notice the double [[]]. Try to see what happens if you transpose a row vector using only [].

In [16]:
col = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]).T
print(col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


**A short note on numpy vectors**
Numpy does not treat vectors and matrices the same. A *true* numpy vector has the shape (k,), . The shape of a numpy array is an attribute, how do you call this attribute for the `row` and `col` arrays? What is the shape of the `row.T` array? 

In [17]:
# Call the shape attribute for the row and col vars. Check the shape of col.T
# FILL IN HERE
np.shape(row)

(9,)

In [18]:
np.shape(col)

(9, 1)

In [19]:
np.shape(col.T)

(1, 9)

In [20]:
np.shape(row.T)

(9,)

To create a matrix, you combine what you have learned to manually create a $3 \times 3$ matrix called x, that has the numbers 0 to 8.

In [21]:
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [22]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create the same $3 \times 3$ using `np.arange()` and np.reshape()

In [23]:
x = np.arange(9).reshape(3, 3)

In [24]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Matrix calculations 
There are several types of matrix calculations available to us with the numpy library, and we will introduce some here.

For matrix **multiplication** you can for the matrices `a` and `b` use `a@b`, `np.dot(a, b)` or `a.dot(b)`

Perform matrix multiplication on the following:
- `row`$\cdot$`row'`, `row'`$\cdot$`row`, `row`$\cdot$`row`;
- `col`$\cdot$`col'`, `col'`$\cdot$`col`, `col`$\cdot$`col`;
- `x`$\cdot$`x`, `row`$\cdot$`col'`, `col`$\cdot$`row'`.

Does the `row` vector behave as you would expect?

In [25]:
print(row@row.T)
print(row.T@row)
print(row@row)

285
285
285


In [26]:
print(col@col.T)
print(col.T@col)
# print(col@col) --> Error: Dimension mismatch

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
[[285]]


In [27]:
print(x*x.T)
print(row*col.T)
# print(col@row.T) --> Error: Dimension mismatch

[[ 0  3 12]
 [ 3 16 35]
 [12 35 64]]
[[ 1  4  9 16 25 36 49 64 81]]


What happens if you use `*` and `/` operators on the same pairs as above? Does the `col` vector behave as you would expect?

In [28]:
print(row.T*row)
print(row*row)
print(row/row.T)
print(row.T/row)
print(row/row)

[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [29]:
print(col.T*col)
print(col*col)
print(col/col.T)
print(col.T/col)
print(col/col)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
[[ 1]
 [ 4]
 [ 9]
 [16]
 [25]
 [36]
 [49]
 [64]
 [81]]
[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111]
 [2.         1.         0.66666667 0.5        0.4        0.33333333
  0.28571429 0.25       0.22222222]
 [3.         1.5        1.         0.75       0.6        0.5
  0.42857143 0.375      0.33333333]
 [4.         2.         1.33333333 1.         0.8        0.66666667
  0.57142857 0.5        0.44444444]
 [5.         2.5        1.66666667 1.25       1.         0.83333333
  0.71428571 0.625      0.55555556]
 [6.         3.         2.         1.5        1.2        1.
  0.85714286 0.75       0.66666667]
 [7.         3.5        2.33333333 1.75       1.4        1.166666

In [30]:
print(row*col)
print(col*row)
print(x/x)
print(row/col)
print(col/row)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
[[nan  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[1.         2.         3.         4.         5.         6.
  7.         8.         9.        ]
 [0.5        1.         1.5        2.         2.5        3.
  3.5        4.         4.5       ]
 [0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
  2.33333333 2.66666667 3.        ]
 [0.25       0.5        0.75       1.         1.25       1.5
  1.75       2.         2.25      ]
 [0.2        0.4        0.6

/var/folders/lh/b_r46db91n9gw9k88wgs406c0000gn/T/ipykernel_23172/1767398005.py:3: RuntimeWarning: invalid value encountered in divide
  print(x/x)


For OLS we need to be able to calculate the inverse. This is done with the `linalg` submodule. Create a new matrix that we can calculate the inverse on. Why can't we take the inverse of `x`\?
*`x` does not have full rank --> not invertible*

In [31]:
v = np.array([[0, 0, 1],
             [1, 0, 0],
             [0, 1, 0]])

In [32]:
print(v)

[[0 0 1]
 [1 0 0]
 [0 1 0]]


What do we normally need to check before we take the inverse? What `numpy.linalg` methods can we use to help us check for this?

In [33]:
r = la.matrix_rank(x)
s = la.matrix_rank(v)

In [34]:
print(r)
print(x.shape, " --> not full rank")
print(s)
print(v.shape, " --> full rank")

2
(3, 3)  --> not full rank
3
(3, 3)  --> full rank


### Stack vectors or matrices together
If you have several 1-D vectors (has the shape (k,)), you can use `np.column_stack()` to get a matrix with the input vectors put together as column.

If you have matrices (or arrays) that are multidimensional (have the shape (k, t)), you can use `np.hstack()` (means horizontal stack). This is very useful if you already have a matrix, and you want to add a vector.

(i) Try to make a matrix with two `row` vectors, this should give you a $9 \times 2$ vector.

(ii) Make a new vector, and add it to the `x` matrix. This should then be a $3 \times 4$ matrix

In [35]:
row1 = np.arange(9)
row2 = np.array([1, 2, 3, 3, 3, 3, 3, 2, 1])
M = np.column_stack((row1, row2))

In [36]:
print("(i)")
print("row1: ", row1)
print("row2: ", row2)
print("M: ", M)
print("M.shape: ", M.shape)

(i)
row1:  [0 1 2 3 4 5 6 7 8]
row2:  [1 2 3 3 3 3 3 2 1]
M:  [[0 1]
 [1 2]
 [2 3]
 [3 3]
 [4 3]
 [5 3]
 [6 3]
 [7 2]
 [8 1]]
M.shape:  (9, 2)


In [37]:
b = np.array([3, 7, 8])
N = np.column_stack((x, b))

In [38]:
print("(ii)")
print("b: ", b)
print("x: ", x)
print("N: ", N)
print("N.shape: ", N.shape)

(ii)
b:  [3 7 8]
x:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
N:  [[0 1 2 3]
 [3 4 5 7]
 [6 7 8 8]]
N.shape:  (3, 4)


### Other methods that you need to know.
The numpy library is vast. Some other methods that are useful are `ones`, `diag`, `diagonal`, `eye`.

## Exercise 1 - Data generation
### 1.1 
Create a synthetic dataset with the following characteristics

\begin{align}
    y_i &= \beta_0 + x_{1i}\beta_1 + x_{2i}\beta_2 + \varepsilon_i
\end{align}

where $\beta_0=1$, $\beta_1 = -0.5$, $\beta_2 = 2$, $x_{1i} \sim \mathcal{N}(0, 4)$, $x_{2i} \sim \mathcal{N}(5, 9)$, $\varepsilon_i \sim \mathcal{N}(0, 1)$, and $(x_{1i},x_{2i})$ and $\varepsilon_i$ are independent, and where $i = 0, ..., 99$. <br>

In [51]:
# Create a seed to always have identical draws.
seed = 42
# Instance a random number generator using this seed.
rng = random.default_rng(seed=seed)
n = 100
b = np.array([1, -0.5, 2]).reshape(-1, 1)

# Make random draws from a normal distribution.
def random_draws(n):
    x0 = np.ones((n, 1)),
    x1 = rng.normal(loc=0, scale=2, size=(n, 1)),
    x2 = rng.normal(loc=5, scale=3, size=(n, 1)),
    eps = rng.normal(loc=0, scale=1, size=(n, 1))
    
    # Stack the single columns into a matrix, 
    X = np.vstack((x0, x1, x2))
    
    return X, eps

X, eps = random_draws(n)
print(b)
# Create y using the betas, X and eps.
y = X.T@b + eps

# Does y have the dimensions you expect?
print(y.shape)

[[ 1. ]
 [-0.5]
 [ 2. ]]
(1, 100, 1)


### 1.2 
Imagine that you had not generated the dataset yourself, but that you were given a similar data set that was already collected (generated) and ready to analyze. What would you observe and not observe in that data set?

In [ ]:
# Observe: X, y
# Non-observables: eps

## Exercise 2 - OLS
### 2.1
Remember the mathematical equation for OLS estimation, as we will later use it to estimate the beta coefficients with the data from the previous exercise.<br>
**Write out the OLS estimator in matrix form:**


$\hat{\boldsymbol{\beta}} = \beta + \left( N^{-1} \sum^N_{i=1} \mathbf{x}_i' \mathbf{x}_i\right)^{-1} \left( N^{-1} \sum^N_{i=1} \mathbf{x}_i' u_i\right) $ 

$\Rightarrow \hat{\beta} = (\mathbf{X}'\mathbf{X})^{-1}\mathbf{X}'\mathbf{Y} $


*Hint: Look it up on p.57 in Wooldridge*

### 2.2
To perform inference on the OLS estimators, we need to calculate the standard errors for the previously estimates OLS coefficients. Again, make sure you remember its equation, *and write up the OLS standard errors in matrix form:*

$\mathbf{\widehat{Var(\boldsymbol{\hat{\beta}})}} = \hat{\sigma}^2 (\mathbf{X}'\mathbf{X})^{-1}$, 

for $\hat{\sigma}^2 = \frac{SSR}{N-K}$, <br>

where $SSR = \sum_{i=0}^{N - 1} \hat{u}^2_i$, $N$ is the number of observations, and $K$ is the number of explanatory variables including the constant.

*Hint: Look it up on p.60 in Wooldridge* <br>
*Hint: Remember that the variance estimate is a function of $\hat{\sigma}^2$, which is calculated using SSR*

### 2.3
Estimate $\boldsymbol{\hat{\beta}}$ from the synthetic data set. Furthermore, calculate standard errors and t-values (assuming that the assumptions of the classical linear regression model are satisfied).

In [73]:
def ols_estimation(y, X):
    # Make sure that y and X are 2-D.
    y = y.reshape(-1, 1)
    if len(X.shape)<2:
        X = X.reshape(-1, 1)

    # Estimate beta
    b_hat = la.inv(X.T @ X) @ (X.T @ y)

    # Calculate standard errors
    residual = y - X@b_hat
    sigma = (residual.T@residual)/(X.shape[0]-X.shape[1])
    varb = sigma * la.inv(X.T@X)
    se = np.sqrt(np.diag(varb))

    # Calculate t-values
    t_values = b_hat/se
    
    return b_hat, se, t_values

b_hat, se, t_values = ols_estimation(y, X)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 100 is different from 3)

Python stores vectors as one-dimensional rather than two-dimensional objects. This can sometimes cause havoc when we want to compute matrix products. Compute the outer and inner products of the residuals from above using np.inner() and np.outer(). Compare these with your computed outer and inner products when using matrix multiplication @. When computing outer and inner products of a column vector, a, recall that a'a is the inner product and aa' is the outer product.

In [ ]:
res = # FILL IN HERE
inner = # FILL IN HERE
outer = # FILL IN HERE
matmul_inner = # FILL IN HERE
matmul_outer = # FILL IN HERE

print('res shape:         ', res.shape)
print('inner shape:       ', inner.shape)
print('outer shape:       ', outer.shape)
print('matmul_inner shape:', matmul_inner.shape)
print('matmul_outer shape:', matmul_outer.shape)

Now if we flatten the residuals to be stored in Python's default mode (i.e. one-dimensional) what happens?

In [ ]:
res = res.flatten()
inner = # FILL IN HERE
outer = # FILL IN HERE
matmul_inner = # FILL IN HERE
matmul_outer = # FILL IN HERE

print('res shape:         ', res.shape)
print('inner shape:       ', inner.shape)
print('outer shape:       ', outer.shape)
print('matmul_inner shape:', matmul_inner.shape)
print('matmul_outer shape:', matmul_outer.shape)

I have written a code to print a table, using the `tabulate` package. You will need to add the row names for this code to work - each row contains a information about the different coefficients on the explanatory variables.

In [ ]:
def print_table(row_names, b, b_hat, se, t_values):
    table = []

    # Make a list, where each row contains the estimated and calculated values.
    for index, name in enumerate(row_names):
        table_row = [
            name, b[index], b_hat[index], se[index], t_values[index]
        ]
        table.append(table_row)

    # Print the list using the tabulate class.
    headers = ['', '\u03b2', '\u03b2\u0302 ', 'Se', 't-value']
    print('OLS Estimates:\n')
    print(tabulate(table, headers, floatfmt=['', '.1f', '.3f', '.3f', '.1f']))

row_names = # Fill in here
print_table(# Fill in here)

Alternatively, you can print a table which you can paste straight into latex using the following code. This uses panda data frames  which we'll cover next week.

In [ ]:
import pandas as pd
dat = pd.DataFrame(zip(b,b_hat.round(4),se.round(4),t_values.round(4)))
dat.columns = ['\u03b2','\u03b2\u0302','se','t-values']
dat.index = ['beta1','beta2','beta3']
print(dat.style.to_latex())

## Exercise 3 - a simple Monte Carlo Experiment
Carry out a Monte Carlo experiment with $S = 200$ replications and $N = 100$ observations to check if the OLS estimator provides an unbiased estimate of $\boldsymbol{\beta}$
### 3.1
Generate 200 data sets similar to what you did in exercise 1, and estimate $\boldsymbol{\beta}$ on each of them.

*Hint:* Start by making prefilling two arrays using `np.zeros`, one array to store the estimated beta coefficients, and one to store the estimated standard errors. What shape should these arrays have?

Then make a loop where each loop makes a random draw, and then estimates on this random draw. And finally stores the estimated coefficients and standard errors.

In [ ]:
# Initialize the variables and lists
s = 200
n = 100

# Allocate memory for arrays to later fill
b_coeffs = np.zeros((s, b.size))
b_ses = np.zeros((s, b.size))

for i in range(s):
    # Generate data
    X, eps = # Fill in here
    y = # Fill in here

    # Estimate coefficients and variance
    b_hat, se, t_values = # Fill in here

    # Store estimates
    b_coeffs[i, :] = # Fill in here
    b_ses[i, :] = # Fill in here

# Make sure that there are no more zeros left in the arrays.
assert np.all(b_coeffs) and np.all(b_ses), 'Not all coefficients or standard errors are non-zero.'

### 3.2
Do the following three calculations:
- Calculate the means of the estimates (means across simulations)
- Calculate the means of the standard errors (means across simulations)
- Calculate the standard error of the MC estimates

In [ ]:
mean_b_hat = # Fill in here
mean_b_se = # Fill in here
mean_mc_se = # Fill in here

### 3.3
Draw a histogram for the 200 estimates of $\beta_1$. This can be done using matplotlib with the method `plt.hist()`.

In [ ]:
# Fill in here